apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hamrss
spec:
  secretName: hamrss-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  dnsNames:
    - hamrss.oddbit.com

  issuerRef:
    name: letsencrypt-production-http01
    kind: ClusterIssuer
